os:
  - linux
  - osx
  
language: rust

sudo: required

rust:
  - beta

before_script:
  - |
      sudo apt-get update -qq &&
      sudo apt-get install -qq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev &&
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

install:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.0/libsodium-1.0.0.tar.gz
  - tar xvfz libsodium-1.0.0.tar.gz
  - cd libsodium-1.0.0 && ./configure --prefix=/usr && make && sudo make install && cd ..

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only beta doc

after_success:
  - travis-cargo --only beta doc-upload
  - travis-cargo coveralls

env:
  global:
  - secure: "ZYISyBQ3ymKmc9N0+DU1hoJtT5IQG/NbiB2G6cqQIEKj+FXbEx4nzy+j2KWWXMn3+1st02Z0L2UYWCC3XDcY66n7J0JDjaaIBK/FMnFbhRt89RnllhtEUDKpcNkjmNek0rTZ7y3MKSxecEHpkWMQDts5vlgZQWfta/Fq0cJ4HaY="
